### PR TITLE
[VA Template] Fixed additional reference to luis service

### PR DESCRIPTION
**Pull request by ryanisgrig**
### Purpose
*What is the context of this pull request? Why is it being done?*
Through end to end testing found one more reference to the incorrect General LUIS model (#1952)

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
n/a 

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
n/a 

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### Deployment Scripts
- [x] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects

### CODE REVIEW

**Comment by lzc850612** [comment]
the lu file is general.lu which is lower case. wouldn't it generate into lowercase model?

**Review by lzc850612 — CHANGES_REQUESTED** [review]
the lu file is general.lu which is lower case. wouldn't it generate into lowercase model?

**Comment by lzc850612** [comment]
> the lu file is general.lu which is lower case. wouldn't it generate into lowercase model?

and if you have to make this change to make the general intents to work, doesn't that mean this never worked before? i don't think that's the case.

**Comment by ryanisgrig** [comment]
I thought the cognitive models I created with the deploy script made them uppercase, or at least that's the json I've been testing with (I don't remember manually changing them). Is that not the case?

**Comment by lzc850612** [comment]
> I thought the cognitive models I created with the deploy script made them uppercase, or at least that's the json I've been testing with (I don't remember manually changing them). Is that not the case?

this is the lu file which is lower case itself. https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Resources/LU/en/general.lu

i don't think the deployment script would make it upper case even if the lu file itself is lower case. We did change the lu files for all the skills to be camelcase instead of lower case. @lauren-mills does the deploy script change casing when creating the luis model? should we change the Lu files in the templates so that they're consistent with the skills change?

**Comment by ryanisgrig** [comment]
I found it, my local copy of this repo has these files as uppercase (🤷🏻‍♂️) but I can see here they should be lowercase. Closing this one and reverting my last PR.

**Pull request closed without merging**
