### PR TITLE
move deploy script to common

### PR DESCRIPTION
**Pull request by lzc850612**
## Description

We have multiple projects that use the deploy.ps1 script. We need to centralize them to one single place for re-usability. This change takes care of that. 
1. Create deploy.ps1 under Templates/Common/Deployment/Scripts
2. Change both VSIX csproj files to do an xcopy for this file before packing
3. Add task for typescript version to do an xcopy for this file before packing
4. Add step to run the task in build.generator-botbuilder-assistant.ts.ps1 script.

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the appropriate unit tests
- [ ] I have tested any new/updated dialogs using Speech in the emulator to ensure the [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) property is set to enable a high quality speech-first experience and the appropriate [InputHints](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) are set correctly. 
- [ ] I have updated related documentation

- [ ] A duplicate issue is filed to track future  work.

- [ ] All languages have been updated
- [ ] You have tested deployment with your new models

### CODE REVIEW

**Review by enzocano — CHANGES_REQUESTED** [review]
Hello @lzc850612, the TypeScript version of `deploy.ps1` is different to the C# version.

**Comment by lzc850612** [comment]
> Hello @lzc850612, the TypeScript version of `deploy.ps1` is different to the C# version.

Can we move the 'deployment' folder inside 'src' so its folder structure is the same as C# version and we can keep the deploy.ps1 file the same, because that feels like the only difference of these two files.

**Comment by enzocano** [comment]
> > Hello @lzc850612, the TypeScript version of `deploy.ps1` is different to the C# version.
> 
> Can we move the 'deployment' folder inside 'src' so its folder structure is the same as C# version and we can keep the deploy.ps1 file the same, because that feels like the only difference of these two files.

For TypeScript projects, the `src` folder should only contains the files that will be 'transpiled' to javascript. Although it is true that this will not present problems at the time of 'transpilation', it would go against TypeScript practices. Maybe we can adapt the script and use a new parameter to decide between the two languages.

In a side note, the `deploy.ps1` script uses `deploy_cognitive_models.ps1`, `luis_functions.ps1`, and `qna_functions.ps1` scripts, so those should be moved to the same folder.

**Comment by lzc850612** [comment]
> > > Hello @lzc850612, the TypeScript version of `deploy.ps1` is different to the C# version.
> > 
> > 
> > Can we move the 'deployment' folder inside 'src' so its folder structure is the same as C# version and we can keep the deploy.ps1 file the same, because that feels like the only difference of these two files.
> 
> For TypeScript projects, the `src` folder should only contains the files that will be 'transpiled' to javascript. Although it is true that this will not present problems at the time of 'transpilation', it would go against TypeScript practices. Maybe we can adapt the script and use a new parameter to decide between the two languages.
> 
> In a side note, the `deploy.ps1` script uses `deploy_cognitive_models.ps1`, `luis_functions.ps1`, and `qna_functions.ps1` scripts, so those should be moved to the same folder.

yeah in theory all the scripts should be extracted out but right now with how they're implemented, it's not easy to move all of them and have them working for both skill and VA. Let me look into how to best do this.

**Comment by darrenj** [comment]
We should align the capitalisation which means we can share the deployment files across both languages. I think thats the only reason for the difference right now?

Sent from my 📱
________________________________

**Comment by lzc850612** [comment]
> We should align the capitalisation which means we can share the deployment files across both languages. I think thats the only reason for the difference right now? Sent from my 📱
> […](#)
> ________________________________ From: Ted <notifications@github.com> Sent: Wednesday, May 8, 2019 1:41:17 PM To: microsoft/AI Cc: Darren Jefford; Review requested Subject: Re: [microsoft/AI] move deploy script to common (#1320) Hello @lzc850612<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzc850612&data=01%7C01%7Cdarrenj%40microsoft.com%7C4f957b697f2b4386e54008d6d3f5854e%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=1uDmwNYSh0Lu%2BeYMJabKQL2PH25VqVIeA9MWu%2F7yblg%3D&reserved=0>, the TypeScript version of deploy.ps1 is different to the C# version. Can we move the 'deployment' folder inside 'src' so its folder structure is the same as C# version and we can keep the deploy.ps1 file the same, because that feels like the only difference of these two files. For TypeScript projects, the src folder should only contains the files that will be 'transpiled' to javascript. Although it is true that this will not present problems at the time of 'transpilation', it would go against TypeScript practices. Maybe we can adapt the script and use a new parameter to decide between the two languages. In a side note, the deploy.ps1 script uses deploy_cognitive_models.ps1, luis_functions.ps1, and qna_functions.ps1 scripts, so those should be moved to the same folder. yeah in theory all the scripts should be extracted out but right now with how they're implemented, it's not easy to move all of them and have them working for both skill and VA. Let me look into how to best do this. — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FAI%2Fpull%2F1320%23issuecomment-490642908&data=01%7C01%7Cdarrenj%40microsoft.com%7C4f957b697f2b4386e54008d6d3f5854e%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=c36arZ7F5RhCChaGGZDg78aqhRhm99Qmrge6PrKr2Mw%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAH7XPIC262S6U2YNHNYDCTLPUM3G3ANCNFSM4HLUXOCA&data=01%7C01%7Cdarrenj%40microsoft.com%7C4f957b697f2b4386e54008d6d3f5854e%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=pPS99ubuEoTjxlHUQvDvI80of4PyDCk2K8fLpn15T2Y%3D&reserved=0>.

i think the goal should be reuse the scripts for both languages, and both skill and va. and i think there's more work needed to make this happen, given how the scripts we have now are implemented. i think we probably need to refactor the scripts so they're agnostic for different languages and whether the bot is a skill or va. they should be driven by one single source of truth such as the ARM template. i've created the issue https://github.com/microsoft/AI/issues/1323 to track this. i'll close this PR.

**Pull request closed without merging**
