### PR TITLE
[Sdk] do not send Handoff to Teams

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Related to #2350 

I am not sure if Teams would support End of Conversation when the sdk is changed and our dev bot keeps broken in Teams now..

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Review by bobokids — APPROVED** [review]

**Comment by darrenj** [comment]
@lzc850612 can you take a look as part of your skills changes? I don't recall Teams having an issue with endofconversation before?

**Comment by lzc850612** [comment]
If we don't send anything (Handoff or EoC) then it'll also be broken in Teams. We should send an email to Teams team to ask for help, to get their answer on which we should use and if neither is supported, they should fix it.

**Comment by lzc850612** [comment]
@darrenj do you have a Teams contact for this?

**Comment by lzc850612** [comment]
Actually, the right fix from us should be that we remove the part to send the activity back to channel for EndOfConversation/Handoff. This should be just something we use internally. @xieofxie, can you make a change to remove line 80 from SkillCallingRequestHandler.cs?

**Comment by xieofxie** [comment]
@lzc850612 OK, removed.

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
