### PR TITLE
[TypeScript][Samples] Fix empty prompt in introStep using Teams

### PR DESCRIPTION
**Pull request by Batta32**
### Purpose
*What is the context of this pull request? Why is it being done?*
Using Teams Channel, the prompt generates an empty `Activity`.

image

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
We improved the validation if there is any parseable options to Activity for the `introStep` method. We took into account the C# [implementation](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs#L345)

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
\-

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

### CODE REVIEW

**Review by darrenj — APPROVED** [review]

**Comment by darrenj** [comment]
Re-based to next branch which given we are now released should be the pattern for csharp and JS moving forward?

**Comment by Batta32** [comment]
@darrenj - it looks great to be in next branch!
Just an observation, we had pointed the PR to master since it's a hotfix for an issue present in the release 1.0.

**Comment by darrenj** [comment]
Let's roll this up with some other changes over the next week and we can push an updated generator?

**Comment by Batta32** [comment]
Sure @darrenj! We've updated the PRs with code changes to branch `next` 😊!

**Review by ryanisgrig — APPROVED** [review]

**Pull request merged**
