### PR TITLE
[TypeScript][Generator] Add special character validation

### PR DESCRIPTION
**Pull request by DiegoCardozo94**
## Purpose
_What is the context of this pull request? Why is it being done?_

Add into `generator-botbuilder` a logic to detect if the name introduced by the user has any special characters or its casing was changed, and show a warning in that case.

## Changes
_Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)_

- Update `Index.js` file in `Skill` and `Assistant` generators.

## Feature Plan
_Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues._
*-*

## Checklist
*-*

### CODE REVIEW

**Review by darrenj — APPROVED** [review]

**Comment by lzc850612** [comment]
the *.cs file changes don't look necessary. did you create the branch out of next branch? for bug fixing it should be out of master branch and against master branch.

**Review by lzc850612 — CHANGES_REQUESTED** [review]
see comment

**Comment by DiegoCardozo94** [comment]
Hi @Izc850612,

Apologies for not seeing this issue before. We created this branch out of `next` and the conflicts appeared when the base branch was changed to `master`. We'll rebase the branch with master so the `C#` changes are not included in these PR.

**Comment by DiegoCardozo94** [comment]
Hi @Izc850612,

We updated the PR, it's ready to be reviewed again.

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
