### PR TITLE
[Power BI] Fix App Insights timespan query that limited all additional timerange parameters

### LINKED ISSUE #1944: Power BI report - date range issue
#### What project is affected?
Analytics / Power BI report

#### What language is this in?
N/A

#### What happens?
When refreshing the report one day a lot of the previous data suddenly dropped off.

Looks like it's due to this line in the EventTelemetry data source definition : `#"timespan"="P7D"`. It restricts the report to only show 7 days data regardless of other factors. I'm guessing something behind the scenes in App Insights has been fixed and that it was just ignoring this parameter previously, but has now started honouring it. Can this param be removed?

#### What are the steps to reproduce this issue?
Refresh a Power BI report which is already loaded with historical telemetry. All but the last 7 days' data drops off.

#### What were you expecting to happen?
Keep showing previous data

### PR DESCRIPTION
**Pull request by ryanisgrig**
### Purpose
*What is the context of this pull request? Why is it being done?*
Close #1944
Removed a timespan parameter on the App Insights query, this only provided 7 days of data to Power BI.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
n/a

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
n/a

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
n/a

### CODE REVIEW

**Review by darrenj — APPROVED** [review]

**Comment by darrenj** [comment]
Should we consider a cherry pick into master for this as it's bug fix?

**Comment by ryanisgrig** [comment]
We can merge into master and then merge down to next after

**Comment by lauren-mills** [comment]
Seems like this is a lot of changes just for a pbi fix. I think if you create the PR against next, then change to master it pulls in all the next commits

**Comment by ryanisgrig** [comment]
@lauren-mills I changed it back to PR against the next branch, and I can cherry pick the commit to master after. The branch was made off of next so that's why it had all those other changes.

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
