### PR TITLE
[TypeScript] Unify BotBuilder dependencies

### PR DESCRIPTION
**Pull request by Batta32**
### Purpose
*What is the context of this pull request? Why is it being done?*
The `botbuilder` dependency includes `botbuilder-core` and `botframework-schema` so it's not necessary to include them explicitly in the `package.json` of the solutions.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
- Remove `botbuilder-core` and `botframework-schema` of `Virtual Assistant`, `Skill`, `BotBuilder-Skill` and `BotBuilder-Solutions`
- Replicate changes in the templates
- Update `package-lock` files
- Update `npm-shrinkwrap` file

image

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
\-

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Review by darrenj — APPROVED** [review]

**Review by lauren-mills — APPROVED** [review]

**Comment by darrenj** [comment]
@Batta32 some conflicts to resolve :)

**Comment by Batta32** [comment]
@darrenj , we already fixed the conflicts! 😊

**Comment by darrenj** [comment]
Some more :-(

**Comment by Batta32** [comment]
@darrenj - Solved!

**Comment by darrenj** [comment]
Not quite :)

**Comment by Batta32** [comment]
Done!

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
