### PR TITLE
Replace ’ to ' in .qna and .lu files and remove trailing spaces

### LINKED ISSUE #3711: Chitchat.qna: Inconsistent character "’" vs "'"
This is causing an encoding issue in our automation script.
Please bulk correct it in the official asset, thanks.

The issue exists in the generated assets across all locales, here is an example for en-us.

image

### PR DESCRIPTION
**Pull request by Batta32**
Fix #3711

### Purpose
*What is the context of this pull request? Why is it being done?*
There are inconsistent characters `’` vs `'` causing encoding issues.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
For C# and TypeScript Virtual Assistant Template / Sample, Skill Template / Sample:
- Replace `’` to `'` in `.qna` files
- Replace `’` to `'` in `.lu` files
- Remove trailing spaces in `.qna`, `.lu`, `.lg` files

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
We manually tested the deploy of the QnA models and the communication with the bots with these changes.

_Successful deployment of a Virtual Assistant with these changes_
image

_Successful communication to the Virtual Assistant with these changes_
image

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

### CODE REVIEW

**Comment by dawwa** [comment]
@Batta32, there is invalid white space as well, e.g.,  the highlighted piece at LINE#1344 is regular whitespace, not sure what is at the end of LINE#1343, please note it's just an example, need a bulk fix for all other files.
image

**Comment by Batta32** [comment]
Thanks @dawwa, we will check this and update the PR.

**Comment by Batta32** [comment]
@dawwa - we already removed the trailing spaces for the `.qna`, `.lu`, `.lg` files for C# and TypeScript bots.

**Comment by dawwa** [comment]
> @dawwa - we already removed the trailing spaces for the `.qna`, `.lu`, `.lg` files for C# and TypeScript bots.

@Batta32 , would you please check the invalid space character in between as well? it's not only about trailing space, there are white spaces that are not consistent, I suspect it's due to Full-width vs half-width, e.g., I would suggest to copy the original white space at the problematic spot as seen below and compare with the regular whitespace you typed in with your keyboard when in English IME, and then bulk replace to capture other spots beyond the trailing ones. 

image

**Comment by Batta32** [comment]
Sure @dawwa! We are currently working on fixing those spaces, thanks for the feedback 😊!

**Comment by Batta32** [comment]
@dawwa - we already removed those inconsistent spaces. Feel free to review it and add your feedback 😊.

**Review by lauren-mills — APPROVED** [review]

**Pull request merged**
