### PR TITLE
[Lib] Skill Middleware update to clear conv state when skill is cancelled

### PR DESCRIPTION
**Pull request by lauren-mills**
### Purpose
*What is the context of this pull request? Why is it being done?*
This change clears out the skill conversation state when it is cancelled by the VA. This prevents data (i.e. responses to prompts) from being stored and reused in the skill after a cancellation.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by ryanisgrig** [comment]
Please rebase against next to capture the refactoring changes

**Review by ryanisgrig — APPROVED** [review]

**Comment by xieofxie** [comment]
Do we need to delete the conversation state? Since many skill states are saved per conversation instead of per user. It seems like once cancelled, they are deleted too (like location, timezone).

Could you provide an example about "data (i.e. responses to prompts) stored and reused in the skill after a cancellation"?

**Review by darrenj — APPROVED** [review]

**Comment by darrenj** [comment]
We should add a documentation item to talk about cancellation state to highlight that Skill developers should not rely on conversation state after a dialog has been completed/cancelled.

**Comment by lauren-mills** [comment]
@xieofxie The issue raised by the customer was around this scenario in the Calendar skill:
- User says "schedule a meeting"
- Bot prompts for contact, and user says a name (this name is stored in conversation state)
- The user cancels
- The calendar skill dialog state is cleared, but conversation state remains
- User says "schedule a meeting" again
- Bot says "Ok, I've added [old contact name] to the meeting."

We shouldn't be persisting anything we need from the user across dialogs in conversation state. Things like location and timezone should be passed from the VA via slots, or saved in user state, because they are user properties

**Pull request merged**
