### PR TITLE
[Skills] Remove redundant lg files

### PR DESCRIPTION
**Pull request by ssss141414**
### Purpose
*What is the context of this pull request? Why is it being done?*
Arranged lg files, so it can remove redundant duplicate lg files.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
Yes.

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by darrenj** [comment]
Thanks - can we get a quick test pass to ensure speech scenarios work as expected - e.g. inputhints, speak versions, etc? Nervous of any regressions that might ocurr?

**Review by darrenj — CHANGES_REQUESTED** [review]
Thanks - can we get a quick test pass to ensure speech scenarios work as expected - e.g. inputhints, speak versions, etc? Nervous of any regressions that might ocurr?

**Comment by ssss141414** [comment]
> Thanks - can we get a quick test pass to ensure speech scenarios work as expected - e.g. inputhints, speak versions, etc? Nervous of any regressions that might ocurr?

Hi,
This PR didn't change any speech scenarios so it should be ok. And to double check, I speak with some main flows in these skills:
    Todo Skill: ShowToDo AddToDo DeleteToDo MarkToDo
    Email Skill: ShowEmail SendEmail ForwardEmail
    Calendar Skill: FindContact ShowEvents UpdateEvent CreateEvent
And I found that inputhints of 'SentSuccessfully' in email skill is incorrect, it should be accepting.
And all the other speechs and inputhints work well.

Thanks!

**Comment by darrenj** [comment]
Thanks!

**Review by darrenj — APPROVED** [review]

**Comment by darrenj** [comment]
@ssss141414 can you resolve the conflicts, we can then merge. Thanks

**Review by lauren-mills — APPROVED** [review]

**Pull request merged**
