### PR TITLE
[Email] Add config for slot filling attribute skip

### LINKED ISSUE #751: Calendar skill skipping prompts in some scenarios
**Project**
Virtual Assistant

**Description**
When using the calendar skill, if you say "schedule a meeting", the skill will then prompt for each piece of required information (i.e. title, content, attendees, time).  However, if you provide any information in the initial utterance, e.g. "schedule a meeting with chris" providing an attendee, the skill doesn't ask for some items. e.g. meeting title, meeting content, duration.

Is this by design??  It seems that the logic the skill is using is checking createHasDetail property (indicating some detail was passed with the initial utterance) and if this is true it is skipping certain properties.

**To Reproduce**
Enter "schedule a meeting with chris" and follow the prompts - default title / content / duration is used.

**Expected behavior**
I think that the skill should only skip over information already provided, but should prompt for anything that is missing.

I am happy to submit a PR for the above if this is not being done by design.

### PR DESCRIPTION
**Pull request by DingmaomaoBJTU**
Close #751 Calendar skill skipping prompts in some scenarios

## Purpose
Make send email flow slot filling configurable as suggested.

## Changes
1. Add config for email subject/email message for send email flow, including default value and skip by default setting.
2. Remove useless read more config.

## Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### CODE REVIEW

**Comment by ryanlengel** [comment]
Thank you for raising a pull request. Please ensure you have have completed the following:

- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

**Comment by ryanisgrig** [comment]
Thank you for raising a pull request. Please ensure you have have completed the following:

- [ ] I have commented my code, particularly in hard-to-understand areas	
- [x] I have added or updated the appropriate tests	
- [ ] I have updated related documentation
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

**Comment by ryanlengel** [comment]
Thank you for raising a pull request. Please ensure you have have completed the following:

- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

**Comment by ryanlengel** [comment]
Thank you for raising a pull request. Please ensure you have have completed the following:

- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

**Comment by darrenj** [comment]
@garypretty If you have a moment can you review this against #751 to see if it gives you the customisation you were after?

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
