### PR TITLE
[Docs] fix links, add data.urls.SkillManualAuth

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Related #2966

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

* fix links
* add data.urls.SkillManualAuth
* use gem liquify

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

Via htmlproofer

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by darrenj** [comment]
Thanks @xieofxie

@ryanlengel can you quickly review please?

**Review by darrenj — APPROVED** [review]

**Comment by ryanisgrig** [comment]
@xieofxie I'm not sure that `jekyll-liquify` will work on the docs site, I've run into issues with using unsupported plugins in the past (I was using `jekyll-toc`). The issue is that while it runs fine locally it is not supported by the server itself. I think there is a workaround where you can push static pages on the site and have it work, but I do not know the specific details of how to implement that.

https://pages.github.com/versions/

**Comment by xieofxie** [comment]
@ryanlengel, I see.. Change to concatenation.

**Review by ryanisgrig — APPROVED** [review]
This is a good approach!

**Pull request merged**
