### PR TITLE
[VA] end skill dialog

### LINKED ISSUE #2970: [VA] overwrite OnEndOfConversationActivityAsync to end Skill Dialog
#### What project is affected?

VA template

#### What language is this in?

C#

#### What happens?

DefaultActivityHandler should overwrite OnEndOfConversationActivityAsync to end Skill Dialog

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Close #2970

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Overwrite OnEndOfConversationActivityAsync

### To Reproduce

Before: 
- Connect VA and POI in master
- Ask POI until finish
- POI(SkillDialog) is still active

After:
- A new trace shows up and POI is finished:
image

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by darrenj** [comment]
@xieofxie Can you provide some background as to this change please?

**Comment by lzc850612** [comment]
If your purpose is to let MainDialog handle the EndOfConversation coming back from skills, it's already been handled by SkillDIalog so MainDialog doesn't need to handle it. It's part of the communication protocol between parent bot and child bot that's internal to the skill dialog and main dialog should know nothing about it.

**Comment by lzc850612** [comment]
and please follow the PR template to fill detailed information so people who reviews the PR has context about it.

**Comment by xieofxie** [comment]
@lzc850612 Sorry, I have added the steps to reproduce.
I tested with VA sample and POI in master branch. It does not work correctly without this modification. Do I miss something? Thanks

**Comment by darrenj** [comment]
@lzc850612 Could you take a look and see if we have a regression? Either with the way the PoI skill has been updated or VA itself?

**Comment by lzc850612** [comment]
looking

**Comment by lzc850612** [comment]
The skill is fine and yes we're missing this specific handler. Thanks @xieofxie for identifying this!

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
