### PR TITLE
added EnterpriseBotSample project

### PR DESCRIPTION
**Pull request by lauren-mills**
## Description

Adding a sample version of the Enterprise Template so people who have already built a project with previous versions can see the latest changes easily.

### CODE REVIEW

**Comment by ryanisgrig** [comment]
How often should this be updated? With each iterative change to the enterprise template or when there is a new release?

**Comment by lauren-mills** [comment]
I think with each update. It just takes a second to recreate the project from the template, and it helps verify that it works as well.

**Comment by lauren-mills** [comment]
It also will help us with bugs that happen between versions

**Comment by ryanisgrig** [comment]
Makes sense!

**Review by ryanisgrig — APPROVED** [review]

**Pull request merged**
