### PR TITLE
[Calendar] Handle more actions after show meetings

### PR DESCRIPTION
**Pull request by KayMKM**
## Purpose
*What is the context of this pull request? Why is it being done?*
Support switch to another flow when showing meeting list.
image

## Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp?*

*Include illustrative screenshots for context if applicable.*

## Tests
*Is this covered by existing tests or new ones? If no, why not?*

## Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### CODE REVIEW

**Comment by ryanisgrig** [comment]
Thank you for raising a pull request. Please ensure you have have completed the following:

- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

**Comment by ryanlengel** [comment]
Thank you for raising a pull request. Please ensure you have have completed the following:

- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

**Comment by darrenj** [comment]
@KayMKM - Thanks. The goal of the change was to enable the user to ask entirely different things after asking say "What meetings do I have" including tasks that are outside of the calendar skill.

e.g. This is the flow we were trying to ensure worked.

- What meetings do I have?
- <Skill Responds> with adaptive card
- What emails do I have?
- <Skill Responds> with adaptive card
- Find me a coffee shop

**Review by lzc850612 — APPROVED** [review]

**Review by darrenj — CHANGES_REQUESTED** [review]
Email discussion :-)

**Comment by bobokids** [comment]
This change is to enable the scenario that after "showing meetings", user can say "update the second one" to start update the second meeting directly. Current flow in Calendar does not support this kind of flexibility, user had to say "read the second meeting" before he/she can update it.

Switching between skills are a different requirement than this PR, which Qiong is working on to add the callback event. We will add the support to switch between skills to Calendar after Qiong's PR is checked in.

for this PR, can we just check it in first for the first scenario above? and then we will submit another PR to enable more context switch after Qiong's PR is in.

**Review by darrenj — APPROVED** [review]

**Pull request merged**
