### PR TITLE
Declare $appName in UpdateLUIS (again)

### PR DESCRIPTION
**Pull request by ericchansen**
* update_cognitive_models.ps1 errors due to this. Fix by declaring $appName in luis_functions.ps1.
* Fix issue #3439

### Purpose

Fixes issue #3439.

### Changes

No significant changes.

### Tests

No tests required for deployment scripts. IMO this repo should create deployment pipelines that utilize these PowerShell scripts to update bots. Then you'd see when this stuff breaks.

### Feature Plan

Not necessary.

#### General
- [x] I have commented my code, particularly in hard-to-understand areas	
- [x] I have added or updated the appropriate tests	
- [x] I have updated related documentation

### CODE REVIEW

**Comment by darrenj** [comment]
Already addressed last week in #3430 - present in next branch. Will be merged into master when we perform a release end of week for the latest C# SDK

**Comment by ericchansen** [comment]
Thanks @darrenj. I'll have to check the next branch instead of master in the future.

**Comment by saikumaru** [comment]
@darrenj the one we addressed last week with my request https://github.com/microsoft/botframework-solutions/pull/3419 was only for samples, but still needs to be addressed for templates.

I just verified and the Next branch dint have this fixed in VA and Skill templates

At Skill
https://github.com/microsoft/botframework-solutions/blob/92c1e4558bf92ac164cf3621e48786466e8618c4/templates/csharp/Skill/Skill/Deployment/Scripts/luis_functions.ps1#L60

At VA
https://github.com/microsoft/botframework-solutions/blob/92c1e4558bf92ac164cf3621e48786466e8618c4/templates/csharp/VA/VA/Deployment/Scripts/luis_functions.ps1#L60

Let me know if otherwise

**Comment by darrenj** [comment]
Templates are updated when we do the release, they are build from the sample directly 😊

**Pull request closed without merging**
