### PR TITLE
use image with route (#1332)

### LINKED ISSUE #1332: [POI] Investigate a static map image with route polygon highlighted
**Is your feature request related to a problem? Please describe.**

The POI skill returns a map image without any indicators of important entities (origin/destination pins, route) and looks very generic.

**Describe the solution you'd like**

According to [Render custom data on a raster map](https://docs.microsoft.com/en-us/azure/azure-maps/how-to-render-custom-data), we may be able to return a map image with the origin/destination route line statically rendered.  Show a snapshot of a map with user's location as well as the target location to provide context on the location of the destination.

**Describe alternatives you've considered**

Other alternatives require Javascript rendering which is not possible for the VA solution.

**Additional context**

### PR DESCRIPTION
**Pull request by xieofxie**
## Purpose
*What is the context of this pull request? Why is it being done?*

Close #1332.

## Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp?*

*Include illustrative screenshots for context if applicable.*

Use a static map image with route.
response

In AzureMapsGeoSpatialService.GetRouteImageAsync, it only returns a string now. If one wants to render a more detailed path, one could make use of [Data in Azure Maps Service](https://docs.microsoft.com/en-us/rest/api/maps/data). However, it is a little complicated to delete data after use.

## Tests
*Is this covered by existing tests or new ones? If no, why not?*

Manually test several routes on different zooms.

## Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

N/A.

### CODE REVIEW

**Review by ryanisgrig — COMMENTED** [review]
Cool this looks good, the red line is a bit jarring. Is there a way to change it's color or width?

I found a small bug, the `VA.Location` event doesn't work as it is looking for `Location` to get coordinates. @lzc850612 this should be switched over right? Should these common events be available from the `Microsoft.Bot.Solutions` package?

In the future, you can link to an issue within the description of your PR by saying "Close #1332" - this will automatically close the issue when the PR is closed as well.

**Comment by xieofxie** [comment]
We could change color or width by lc or lw in [path](https://docs.microsoft.com/en-us/rest/api/maps/render/getmapimage#uri-parameters), but joints could not be modified.
I make the line thinner (4->2) and it looks better:
response
Should we draw something at the start? Technically it could draw pins everywhere with any custom image.

**Comment by bobokids** [comment]
can we add an icon to start location similar to the destination? @ryanlengel. If we can add we may need a design for the icon.

**Comment by ryanisgrig** [comment]
If we can add an icon that would be great
Let's try this hex for the line  #0078d4 (blue)

**Comment by xieofxie** [comment]
> If we can add an icon that would be great
> Let's try this hex for the line #0078d4 (blue)

response
It is rendered in Postman.

**Comment by ryanlengel** [comment]
Followed up offline with a sample URL to use:
https://atlas.microsoft.com/map/static/png?api-version=1.0&layer=basic&style=main&subscription-key=9P73jpx5CyCOkaMuY1MH5t3Umaka30tCxw3TgdKg-dc&width=440&height=240&zoom=14&center=-74.0071144104004,40.7114696502686&pins=default|la15+50|al0.75|cod83b01||'Start'-74.0072326660156 40.7130393981934|'End'-74.00644 40.71056&path=lw2|lc0078d4||-74.0072326660156 40.7130393981934|-74.0073928833008 40.7128601074219|-74.0076675415039 40.7125282287598|-74.0078887939453 40.7122611999512|-74.0081100463867 40.7119789123535|-74.0083694458008 40.711669921875|-74.0086212158203 40.7114105224609|-74.0082015991211 40.7110710144043|-74.0077667236328 40.7108192443848|-74.0073699951172 40.710578918457|-74.0060806274414 40.7098999023438|-74.0056076049805 40.7103996276855|-74.0060424804688 40.7108001708984|-74.00644 40.71056

* Added start/end pins and labels
* Position labels below pins
* Add opacity to labels

image

**Comment by lzc850612** [comment]
> Cool this looks good, the red line is a bit jarring. Is there a way to change it's color or width?
> 
> I found a small bug, the `VA.Location` event doesn't work as it is looking for `Location` to get coordinates. @lzc850612 this should be switched over right? Should these common events be available from the `Microsoft.Bot.Solutions` package?
> 
> In the future, you can link to an issue within the description of your PR by saying "Close #1332" - this will automatically close the issue when the PR is closed as well.

Can you tell me where exactly is looking for 'Location' instead of VA.location? 
also, i don't think the VA.Location event should be part of the Microsoft.Bot.Solutions package. It should be part of custom implementation of VA and Skills.

**Comment by lzc850612** [comment]
> Followed up offline with a sample URL to use:
> 
> * Added start/end pins and labels
> * Position labels below pins
> * Add opacity to labels
> 
> image


Looks good to me and please be sure to include the change that Ryan mentioned in the last comment since that path style definitely looks better.

**Review by lzc850612 — APPROVED** [review]

**Comment by ryanisgrig** [comment]
> > Cool this looks good, the red line is a bit jarring. Is there a way to change it's color or width?
> > I found a small bug, the `VA.Location` event doesn't work as it is looking for `Location` to get coordinates. @lzc850612 this should be switched over right? Should these common events be available from the `Microsoft.Bot.Solutions` package?
> > In the future, you can link to an issue within the description of your PR by saying "Close #1332" - this will automatically close the issue when the PR is closed as well.
> 
> Can you tell me where exactly is looking for 'Location' instead of VA.location?
> also, i don't think the VA.Location event should be part of the Microsoft.Bot.Solutions package. It should be part of custom implementation of VA and Skills.

https://github.com/microsoft/botframework-solutions/blob/master/skills/src/csharp/pointofinterestskill/pointofinterestskill/Dialogs/MainDialog.cs#L162

**Comment by xieofxie** [comment]
> Followed up offline with a sample URL to use:
> [https://atlas.microsoft.com/map/static/png?api-version=1.0&layer=basic&style=main&subscription-key=9P73jpx5CyCOkaMuY1MH5t3Umaka30tCxw3TgdKg-dc&width=440&height=240&zoom=14&center=-74.0071144104004,40.7114696502686&pins=default|la15+50|al0.75|cod83b01||'Start'-74.0072326660156](https://atlas.microsoft.com/map/static/png?api-version=1.0&layer=basic&style=main&subscription-key=9P73jpx5CyCOkaMuY1MH5t3Umaka30tCxw3TgdKg-dc&width=440&height=240&zoom=14&center=-74.0071144104004,40.7114696502686&pins=default%7Cla15+50%7Cal0.75%7Ccod83b01%7C%7C'Start'-74.0072326660156) 40.7130393981934|'End'-74.00644 40.71056&path=lw2|lc0078d4||-74.0072326660156 40.7130393981934|-74.0073928833008 40.7128601074219|-74.0076675415039 40.7125282287598|-74.0078887939453 40.7122611999512|-74.0081100463867 40.7119789123535|-74.0083694458008 40.711669921875|-74.0086212158203 40.7114105224609|-74.0082015991211 40.7110710144043|-74.0077667236328 40.7108192443848|-74.0073699951172 40.710578918457|-74.0060806274414 40.7098999023438|-74.0056076049805 40.7103996276855|-74.0060424804688 40.7108001708984|-74.00644 40.71056
> 
> * Added start/end pins and labels
> * Position labels below pins
> * Add opacity to labels
> 
> image

OK, I have updated the code with Bing translated 'Start', 'End'. It would be better to share URL privately next time since it contains a private subscription-key.

**Comment by darrenj** [comment]
VA.Location is fine to use within the Skill. If developers have a strong opinion on a different event they can change . I would like to define a set of canonical common events that we use across the solution (including this) so we are consistent.

**Pull request merged**
