### PR TITLE
[POI] update lu files

### LINKED ISSUE #2213: [POI] Improve LUIS model for greater understanding and scalability
#### Is your feature request related to a problem? Please describe. 
* The language model captures too many utterances now
* It is not scalable enough when new unmatched entities are found
* It does not follow the naming conventions used by other skills

##### Intents
* Remove NAVIGATION_CANCEL_ROUTE
* Rename NAVIGATION_FIND_PARKING to FindParking
* Rename NAVIGATION_FIND_POINTOFINTEREST to FindPointOfInterest
* Rename NAVIGATION_ROUTE_FROM_X_TO_Y to GetDirections

Intents should understand the different between a user saying something like:
"Find me the nearest coffee shop" -> FindPointOfInterest
"Take me to the nearest coffee shop" -> GetDirections

##### Entities
* Rename ADDRESS to Address
* Rename KEYWORD to Keyword
* Rename POI_TYPE to PoiDescription
* Rename ROUTE_TYPE to RouteDescription

* Add phrase lists to be used as Keyword entities, this way when we need to add new brands they can go into the phrase list instead of being individually labeled.
    * Cusine (Italian, Spanish, Japanese, Polish, etc.)
    * Brand (McDonalds, Panera Bread, Lowe's T-Mobile, etc.)
    * Category (airport, bank, book store, museum, train station, etc.)

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Close #2213 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

* rename intents and entities
* remove cancel
* organize utterance by verb
* add keyword_brand, keyword_cusine, keyword_category
* update tests

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

Yes

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

After #2250 is merged

#### General
- [x] I have commented my code, particularly in hard-to-understand areas	
- [x] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [x] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by xieofxie** [comment]
@ryanlengel One finding about the utterances:

In GetDirections, there is "get to" and in FindPointOfInterest, there is "get someone something". Sometimes Luis could not tell the difference between them.

Should we leave them as it is? Or remove one of them.

**Comment by xieofxie** [comment]
Not necessary for next

**Comment by ryanisgrig** [comment]
@xieofxie I'm inclined to remove the GetDirections example and keep the FindPointOfInterest one. Since GetDirections is new we can scale that one out as needed, but FindPointOfInterest intents will yield more options in the conversation and are a better place to start. Is there enough training data for other GetDirections intents to reliably work?

**Comment by xieofxie** [comment]
OK, other keywords are bring to, direct/directions, drive, go, guide, head, navigate/navigation, point, route, take, way. They are quite different from others, so it is fine.

**Comment by xieofxie** [comment]
OK, move "get to" to find poi intent.

**Review by ryanisgrig — APPROVED** [review]

**Review by bobokids — APPROVED** [review]

**Pull request merged**
