### PR TITLE
[TypeScript][Samples/Templates] Update the SDK dependencies

### PR DESCRIPTION
**Pull request by Batta32**
## Purpose
_What is the context of this pull request? Why is it being done?_
Update the SDK dependencies version for the Samples and Templates

## Changes
_Are there any changes that need to be called out as significant or particularly difficult to grasp?_ (Include illustrative screenshots for context if applicable.)

We updated the following files in `skill/assistant templates` & `samples assistant/skill`:
- `package.json` 
- `package-lock.json`
	
image

## Tests
_Is this covered by existing tests or new ones? If no, why not?_
Yes, it's covered by existing tests.

## Testing Steps
1. Go to `.\templates\Virtual-Assistant-Template\typescript\samples\sample-assistant` open a terminal and execute `pwsh.exe -File deployment\scripts\deploy.ps1`.
1. Execute `npm install` to install the dependencies.
1. Execute `npm run build`.
1. Execute `npm run test` to check that the test are passing successfully.
1. Execute `npm run start`.
1. Verify that the behavior of the bot hasn't changed having led to the latest version of the libraries.

## Feature Plan
_Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues._

Continued updating of the dependencies in `BotBuilder-Skills` and `BotBuilder-Solutions`

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Review by lauren-mills — APPROVED** [review]

**Comment by lzc850612** [comment]
this should be against next branch since master branch is the one that's shipped last plus bug fixing. shouldn't have changes that updates SDK versions for master

**Comment by dfavretto** [comment]
@lzc850612 this PR points to `master` since it has the bump on the version of `botbuilder-skills` and `botbuilder-solutions` which are mandatory for fixing several issues, but as you say, the bump of SDK dependencies can point to `master`.
If you want, we can split this PR in two:
- First one bumping only `botbuilder-skills` and `botbuilder-solutions`, pointing to `next` for the bugfixing.
- Second one bumping `SDK dependencies`, pointing to `master`.

Does that sound good for you?

**Comment by darrenj** [comment]
Let's go with this into master as typescript is playing catchup with our last release compared to c#

**Comment by Batta32** [comment]
Thanks @darrenj, we'll test the recently `4.4.8` version for `botbuilder-libs` of [myget](https://botbuilder.myget.org/gallery/aitemplates/) and we will let you know once we finish in order to merge this Pull Request

**Comment by dfavretto** [comment]
@darrenj this has been updated with the latest stable version `4.4.8` from `botbuilder-skills` and `botbuilder-solutions`

**Review by darrenj — APPROVED** [review]

**Pull request merged**
