### PR TITLE
[C#][Skill] Add Functional Tests

### PR DESCRIPTION
**Pull request by DiegoCardozo94**
Related to #3290 

### Purpose
*What is the context of this pull request? Why is it being done?*
There is no functional test applied for Skill in C#.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
- Add functional test project in the C# Skill and functionality
- Add `yml` file for the C# Skill
- Add documentation for the `yml` file

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
*-*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
*-*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [X] I have added or updated the appropriate tests	
- [X] I have updated related documentation

### CODE REVIEW

**Comment by ryanisgrig** [comment]
Hey @DiegoCardozo94, I've got a draft PR #3502 with regards to enhancements on the Direct Line functional tests for both C# VirtualAssistantSample/SkillSample. It's using the Direct Line client from the SDK team's functional tests and adds test cases more conversational scenarios. It's still in progress as I'm testing it against the nightly scratch deployment. We should use that one and then apply the `README`/`yml` files here.

**Comment by DiegoCardozo94** [comment]
Sure @ryanlengel! We identified the mentioned PR #3502 and we took into account the changes applied in `DirectLineClientTests` that we added in this PR.

We converted this PR to draft and as soon as the PR #3502 is merged, we will update this one to apply the `README/yml` files 😊.

**Comment by peterinnesmsft** [comment]
@DiegoCardozo94, just to confirm, it sounds like we are saying that the updates to the README and yml files in this pull request should be applied in #3502, but otherwise once that is done, we can converge on that PR. Is that correct?

**Comment by Batta32** [comment]
@peterinnesmsft - exactly, the YML/README can be added in the PR #3502 as you mentioned. Also, we can wait to have the PR #3502 merged and use this PR to add the YML/README.

Let us know which is the best approach to follow here 😊.

**Comment by ryanisgrig** [comment]
@Batta32 I will copy the YML/README into #3502 and close this when that is ready!

**Comment by lauren-mills** [comment]
Closing - outdated

**Pull request closed without merging**
