### PR TITLE
display full ARM validation error feedback

### PR DESCRIPTION
**Pull request by h2floh**
##  #Purpose
*What is the context of this pull request? Why is it being done?*
Allowing a better error feedback for deployment errors.

## Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp?*
No

### CODE REVIEW

**Comment by ryanisgrig** [comment]
Thank you for raising a pull request. Please ensure you have have completed the following:

- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have updated related documentation
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

**Comment by darrenj** [comment]
Do you have an example of an error condition that the "error message" currently being shown wasn't correct and what the raw JSON approach shows instead?

**Comment by h2floh** [comment]
yes, while deployment use a Storage Account name which is already in use by someone else. You get a cryptic error message. If you read the full json output error reason is stated crystal clear: **storage account Name already in use**

And no I did not replicated the changes in the sample projects.

**Comment by lauren-mills** [comment]
Hi @h2floh there are a lot of other changes in the PR besides just the deployment change, so I'm going to close this. I'll include your change to the deployment script with another round of changes this week.

**Pull request closed without merging**
