### PR TITLE
Sync dispatch model with new cognitive models

### LINKED ISSUE #1431: Unable to add additional QnA Maker or LUIS Endpoint using steps in documentation
## Project
Virtual Assistant Template

**Language**: C#

## Description
Additional Knowledge base is not added to the dispatch model when calling the following command

 `update_cognitive_models.ps1 -RemoteToLocal`

The documentation for adding [another QnA endpoint](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeassistant.md#add-an-additional-knowledgebase) states to call the update_cognitive_models.ps1 script, this doesn't add the new endpoint to the dispatch model and the next step to update the MainDialog.cs file cannot be completed.

## To Reproduce
Follow the documention for adding [another QnA endpoint](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeassistant.md#add-an-additional-knowledgebase).

Note at the end of step 2, the Luis.DispatchLuis.Intent enum does not update with the new endpoint.

## Expected behavior
Adding a new cognitive model should update the dispatch model as well. This can be tested by investigating the Luis.DispatchLuis.Intent enum as a new intent should be created.

### PR DESCRIPTION
**Pull request by NathanNZ**
## Description
When running the following command:
  `update_cognitive_models.ps1 -RemoteToLocal` 

Any new cognitive models should be added to the existing dispatch model, this allows users to refer to the new endpoint in the resulting luisgen'd class file.

### Bug Fixes
Closes #1431 

## Testing Steps
Follow the documention for adding [another QnA endpoint](https://github.com/microsoft/botframework-solutions/blob/master/docs/tutorials/csharp/customizeassistant.md#add-an-additional-knowledgebase).

The new endpoint should show in the LuisGen'ed dispatch model.

## Checklist
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have updated related documentation _(no documentation needs to be updated as this fixes the existing documentation)_

### CODE REVIEW

**Comment by NathanNZ** [comment]
I believe this solves the issue without any side effects, let me know if I've overlooked something!

**Comment by darrenj** [comment]
Hi @NathanNZ - thanks for taking the time to look at this. You are indeed right, whilst the update_cognitive_models.ps1 script when run with `RemoteToLocal` will update local files with changes/new KBs it just refreshes the dispatcher which has it's own view of the world and doesn't reflect the new dispatch type :-(

Appreciate the PR!! My only concern is the script will try and add all LUIS/QnAmaker sources to dispatch even if they exist - dispatch will error however this is stepped over and execution continues so I think this is fine based on my testing:

```
LUIS app :8340b356-4122-4184-8e9e-d2d105a5ead2 already added to djassistant2testen_Dispatch.dispatch
QnA kb id:034702e0-d92c-431b-a5e3-7dc870690534, name:chitchat already added to djassistant2testen_Dispatch.dispatch
QnA kb id:0179bf9e-0dc2-4d15-baf5-fcd3e7304ef7, name:faq already added to djassistant2testen_Dispatch.dispatch
```

Perhaps add a comment to highlight this expected behavior. @lauren-mills any thoughts?

**Comment by NathanNZ** [comment]
No worries, I believe that's mainly an informational message as it's not throwing up any erroneous exit codes - but I fully agree there should probably be a comment slapped on there that mentions the assumed idempotent behavior to help any future developers reason around the code. Happy to patch that within the next 24 hours.

I'd admit there probably is a good discussion to be had about putting the dispatcher syncing logic somewhere else - especially since this might be needed when authoring LU files locally (and potentially other places such as deploy?) however I don't have a good enough grasp of the entire solution yet and this seems to be a fairly simple workaround to unblock others following through the docs 👍

**Comment by NathanNZ** [comment]
All done :+1:

**Comment by darrenj** [comment]
Looks great - one last thing, I can't seem to push my own commit into your fork so need you to do it :-)

Can you copy/paste this file in your PR to the following locations? We want to centralise them so you only have one copy to maintain but that causes a headache around automated builds so still figuring that one out.

- templates\Virtual-Assistant-Template\csharp\Sample\VirtualAssistantSample\Deployment\Scripts
- templates\Skill-Template\csharp\Template\Skill\Deployment\Scripts
- templates\Skill-Template\csharp\Sample\SkillSample\Deployment\Scripts

We'll handle the typescript changes separately.

Thanks

**Comment by NathanNZ** [comment]
No worries, should be all there now

**Review by darrenj — APPROVED** [review]

**Pull request merged**
