### PR TITLE
fix skill middleware handling of SkillContext

### PR DESCRIPTION
**Pull request by lzc850612**
## Description

In our SkillMiddleware, it cannot convert the activity.Value to SkillContext directly. We need to explicitly deserialize it. 

It appears the Slot definition's constructor will cause the Slots not being deserialized properly. Removing it to fix the issue.

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the appropriate unit tests
- [ ] I have tested any new/updated dialogs using Speech in the emulator to ensure the [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) property is set to enable a high quality speech-first experience and the appropriate [InputHints](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) are set correctly. 
- [ ] I have updated related documentation

- [ ] A duplicate issue is filed to track future  work.

- [ ] All languages have been updated
- [ ] You have tested deployment with your new models

### CODE REVIEW

**Comment by darrenj** [comment]
Can we just not add a default constructor for serialization purposes? Otherwise I think you'll break other parts of the implementation?

**Review by darrenj — CHANGES_REQUESTED** [review]
Can we just not add a default constructor for serialization purposes? Otherwise I think you'll break other parts of the implementation?

**Comment by lzc850612** [comment]
> constructor

removing the constructor will break more. There's a lot of code using that constructor.

why do you think it will break other parts? I would think explicitly deserializing here is a clearer thing to do rather that casting from a string that's deserialized over the wire which is not gonna work.

**Comment by darrenj** [comment]
The constructor with parameters was deliberately put there to simplify the slot implementation if I recall correctly, if you need a default constructor for serialization then add that in addition rather than removing?

**Review by darrenj — APPROVED** [review]

**Pull request merged**
