### PR TITLE
Adding reference to minimum node requirement for Bot Framework CLI

### LINKED ISSUE #3695: Errors in deployment of Virtual Assistant template project
#### What project is affected?

Project created from Virtual Assistant template in VS Community 2019 (16.7.6) 

#### What language is this in?

C#

#### What happens?

Failures occur during QnA cognitive model deployment, Azure resources and steps were successful up to this point.  Continued failures with retry occured during the QnA steps, I cancelled the deployment script and checked the logs.

#### What are the steps to reproduce this issue?

Followed steps here exactly: 
https://microsoft.github.io/botframework-solutions/virtual-assistant/tutorials/create-assistant/csharp/1-intro/

- Running Windows 10
- Installed Virtual_Assistant_and_Skill_Templates.4.9.1.2.vsix
- Commands run in an elevated PS window (7.0.3), Azure CLI 2.14.0

#### What were you expecting to happen?

Deployment to complete without errors...

#### Can you share any logs, error output, etc.?

From `deploy_cognitive_models_log.txt`:

AZ CLI passes minimum version. Current version is 2.14.0
test-virtual-assistant-boten-us_Dispatch.dispatch created
[ERROR] Error happened when parsing qna section: Invalid regular expression: /^```(markdown)?\r*\n(?<answer>(.|\n|\r\n|\t| )*)\r?\n.*?```$/: Invalid group
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Chitchat.json'
[ERROR] Error happened when parsing qna section: Invalid regular expression: /^```(markdown)?\r*\n(?<answer>(.|\n|\r\n|\t| )*)\r?\n.*?```$/: Invalid group
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Faq.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Faq.json'
ENOENT: no such file or directory, lstat 'C:\Users\andre\source\repos\VirtualAssistant1\VirtualAssistant1\VirtualAssistant1\Deployment\Resources\QnA\en-us\Faq.json'

#### Any screenshots or additional context?

Confirmed those json files referenced in errors do not exist - there are .qna files present in those directories however.

### PR DESCRIPTION
**Pull request by veatcha**
Closes #3695 

### Purpose
*What is the context of this pull request? Why is it being done?*

Updating tutorial documentation to include minimum required Node version documented for Bot Framework CLI

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

No.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

No - simple documentation update.

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [x] I have updated related documentation

### CODE REVIEW

**Review by peterinnesmsft — APPROVED** [review]

**Comment by Batta32** [comment]
Thanks @veatcha for creating this PR, we already applied the same changes in the PR #3702 (see [commit](https://github.com/microsoft/botframework-solutions/pull/3702/commits/9181a9a8a64abc8fdf27f4cff1086f5e43f677fd)) which is related to the issue #3689.

If you are okay, we can close this Pull Request as the changes are contained in the other PR 😊.

**Comment by veatcha** [comment]
No problem here, good that the fix is in either way - this was my first public PR...but there will be others!

**Comment by Batta32** [comment]
Thanks @veatcha 😊!

@peterinnesmsft - we can close this PR as the changes are applied in the PR #3702 too.

**Comment by Batta32** [comment]
I'm closing this PR as the changes are applied in the PR #3702

**Pull request closed without merging**
