### PR TITLE
01/enterprise typescript auth fix

### PR DESCRIPTION
**Pull request by 01**
## Description

Minor fix to make Authentication Dialog functional. It was missing an import, and the documentation had wrong class name.

### CODE REVIEW

**Review by enzocano — APPROVED** [review]
Thanks for your contribution @01, I reviewed your changes and they look good.

**Comment by lzc850612** [comment]
Looks like you submitted this PR from your own fork which caused the CLA review issue. Can you submit the PR in the microsoft/AI repo directly? Let us know if you don't already have access to do so.

**Review by lzc850612 — CHANGES_REQUESTED** [review]
Need to submit the PR from microsoft/AI repo instead of your own fork, to prevent potential issues.

**Comment by 01** [comment]
Actually the issue I believe is the signing of the CLA license. I need to look into my own companies policy on this.

**Pull request closed without merging**
