### PR TITLE
[POI] simply move Services to SkillServiceLibrary

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Related to https://github.com/microsoft/botframework-solutions/issues/2428

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Simply move AzureMapsGeoSpatialService, FoursquareGeoSpatialService into SkillServiceLibrary without careful adjustments.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Review by ryanisgrig — APPROVED** [review]

**Comment by lzc850612** [comment]
Is SkillServiceLibrary project being used by skills other than POISkill? If not it should not be a shared library it should be just a dependency library used by POISkill as part of POISkill. Refactoring is good but we shouldn't be inventing them. we can always make the library a shared one when we see the need in the future.

Let's make POISkill a folder in VisualStudio and put the new project in that folder together with the current POISkill project.

**Review by lzc850612 — CHANGES_REQUESTED** [review]
see comment

**Comment by ryanisgrig** [comment]
@lzc850612 this is going to be a shared library, as multiple skills use Azure Maps APIs now, and is the first step in this process.
Please leave the PointOfInterestSkill project in it's current directory, as we have build dependencies on this structure.

**Comment by xieofxie** [comment]
So I don't need to rename, right?

Also move tests in, depends on https://github.com/microsoft/botframework-solutions/pull/2581 now

**Comment by ryanisgrig** [comment]
I think this PR should be postponed until after Ignite, so it can take into account the additional refactoring work for other Skills. Does anyone else have an opinion on this?

**Review by lzc850612 — APPROVED** [review]

**Comment by xieofxie** [comment]
Hi @lzc850612, what's happened with Validation? How could it be fixed? Thanks~

**Comment by lzc850612** [comment]
> Hi @lzc850612, what's happened with Validation? How could it be fixed? Thanks~

never saw this error before. Do you see this error when running the tests locally?

**Comment by xieofxie** [comment]
@lzc850612 After adding SkillServiceLibrary, POI test will depend on SkillServiceLibrary.Tests.dll. So it copies one to its own folder and Validation will try to run it.

However, it could not be run because POI test uses framework Microsoft.AspNetCore.App while SkillServiceLibrary test uses Microsoft.NETCore.App. (Yet it could be referenced and used)

One way to fix this is to exclude these copied SkillServiceLibrary.Tests.dll in the Validation pipeline explicitly.

What's your idea? Thanks~

**Comment by lzc850612** [comment]
> @lzc850612 After adding SkillServiceLibrary, POI test will depend on SkillServiceLibrary.Tests.dll. So it copies one to its own folder and Validation will try to run it.
> 
> However, it could not be run because POI test uses framework Microsoft.AspNetCore.App while SkillServiceLibrary test uses Microsoft.NETCore.App. (Yet it could be referenced and used)
> 
> One way to fix this is to exclude these copied SkillServiceLibrary.Tests.dll in the Validation pipeline explicitly.
> 
> What's your idea? Thanks~

It looks to me that the problem is that POI.Tests shouldn't reference SkillServiceLibrary.Tests. These two projects are both tests so one shouldn't reference the other. If there's anything that POI.Tests wants to use, it shouldn't be in a separate class library that is referenced by both test project.

**Comment by xieofxie** [comment]
@lzc850612 right.. I separate fakes to SkillServiceLibrary.Fakes.

**Comment by lzc850612** [comment]
You can merge it now

**Pull request merged**
