### PR TITLE
Added extension methods for spoken versions of dates and ILists and updated the CreateEventDialog

### PR DESCRIPTION
**Pull request by gabog**
## Description
Created a ToSpeechString extension method of IList<T> that allows  your to enumerate items in a list for use in the speak property of a response.
Created a ToSpeechDateString() and a ToSpeechTimeString() extension method for DateTime to create a string that can be used in a spoken response with dates and times.
Added unit tests for the methods.
Updated the CreateEventDialog to use these methods.
Updated some response strings in CreateEventDialog to make it more fluent.
Fixed several stylecop violations in CreateEventDialog.

## Testing Steps
Create a meeting using speech from the emulator and check the spoken responses (especially the create meeting summary).

### CODE REVIEW

**Comment by gabog** [comment]
Hi, a couple more changes in the PR that I forgot to mention:

- I added a CommonStrings.resx with some of the words that are needed to build spoken dates, time and lists (the resx contains things like And, Or, At, etc.) I put the Spanish version for it but we may need the german and Chinese versions too for completeness, depending on what we are targeting.
- I also added a prebuild step to the VirtualAssistant.csproj that xcopies the skills binaries and resources to the bin assistant's bon directory, this saved me time during testing (a rebuild on the assistant project makes sure everything we need to test the skill from within assistant is in the bin directory).

**Review by darrenj — APPROVED** [review]
@gabog Could you also add a commit for CommonStrings.resx files for French, Italian, German, and Chinese (Simplified). At this time you can just use the bing translator to get things started ahead of a formal (human) translator pass. Thanks

**Comment by gabog** [comment]
sure, will do that later today.

**Comment by gabog** [comment]
done @darrenj, I did my best with Chinesebut I think we are going to revisit that, best thing would be to get someone that speaks Chinese, write some unit tests in  DateTimeExTests.cs and add whatever special cases and resource strings we need there.

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
