### PR TITLE
POI improve language model (#1987)

### LINKED ISSUE #1987: [Point of Interest] Improve language model to capture more POI entities
#### Is your feature request related to a problem? Please describe. 
The Point of Interest Skill can match generic entities like "coffee shop"," pharmacy", "grocery store", etc. but when it comes to displaying specific businesses it is not well trained.

#### What is the solution you are looking for?
Point of Interest LUIS app should be able to capture the POI entities a user has asked for, either by providing a greater variety of training data or introducing patterns to pick up what would come after "find XYZ"

#### Is there any other context you can provide?
Selfhost testers have filed related issues for queries like:
"Where is the nearest Lowe's"
"Where is the nearest Papa John's"

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Close #1987 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Add some utterances.
Add a pin for poi image by azure map.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

Test "Where is the nearest Lowe's", "Where is the nearest Papa John's"

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by ryanisgrig** [comment]
Can you PR against the next branch?

**Comment by xieofxie** [comment]
OK, changed. Currently maybe we have to update luis case by case.

As investigation shows, FourSquare's **search** api is bad for category while **explore** is bad for name. It might be better to only use Azure Maps in deployment for testing.

**Review by lzc850612 — APPROVED** [review]

**Review by lauren-mills — APPROVED** [review]

**Comment by lauren-mills** [comment]
@xieofxie can you update the tests to reflect these changes?

**Comment by xieofxie** [comment]
OK, updated~

**Pull request merged**
