### PR TITLE
[Skills] use single comma for scopes

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Close https://github.com/microsoft/botframework-solutions/issues/2281

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Use single comma for scopes. 

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Review by lzc850612 — CHANGES_REQUESTED** [review]
Have you tested if the change to all the scopes still works for OAuth? The ABS token service will use the scopes setting so we need to make sure the change doesn't break any existing service.

It's nice to get them cleaned up though :)

**Comment by xieofxie** [comment]
Oops, it seems that botskills only supports ', ' instead of ',', so I actually only modify google ones (and tested them).

Create a pr to change to only ',' https://github.com/microsoft/botframework-solutions/pull/2575

**Review by lauren-mills — APPROVED** [review]

**Review by darrenj — APPROVED** [review]

**Comment by xieofxie** [comment]
@lzc850612 please check the change request~

**Comment by lzc850612** [comment]
> @lzc850612 please check the change request~

you still have the change on the graph scope with comma, have you tested if it works as per my previous comment?

**Comment by xieofxie** [comment]
> > @lzc850612 please check the change request~
> 
> you still have the change on the graph scope with comma, have you tested if it works as per my previous comment?

Tested~ I just figured out space works for 'az bot authsetting create' not 'az ad app update' inside botskills, so actually it was somehow buggy.

**Review by lzc850612 — APPROVED** [review]

**Pull request merged**
