### PR TITLE
Enterprise Bot Tests

### PR DESCRIPTION
**Pull request by lauren-mills**
## Description
Close 
### Maintenance
Added unit tests to the Enterprise Template:
•	Intro Card
•	Greeting
•	Help
•	Escalate
•	Onboarding
•	Onboarding_Cancel
•	Intro card (localised)

## Testing Steps

1. Copy EnterpriseBotTemplate folder contents to "%USERPROFILE%\Documents\Visual Studio 2017\Templates\ProjectTemplates\Visual C#"
1. In Visual Studio, select File > New > Project
1. Click the "Enterprise Bot Template" in the Bot category
1. Rebuild the project (to copy content files to Test project output)
1. Verify all tests pass

## Checklist

- [ ] I have added or updated the appropriate unit tests
- [ ] I have updated related documentation

### CODE REVIEW

**Comment by darrenj** [comment]
Works for me - however I am seeing two warnings relating to the telemetry class. I've checked in changes in another PR but @ryanlengel should confirm they are correct

 image

**Review by darrenj — COMMENTED** [review]
Worked for me however some tests (reliant on response files and card JSON) did fail first time until I did rebuild-all as they couldn't be found in the project output directory

**Comment by lauren-mills** [comment]
We’re aren’t actually using the response files in this template, it’s just the intro card. Wasn’t sure if moving to embedded resources was too much just for the intro cards since it makes the logic a bit more complicated

**Comment by darrenj** [comment]
Odd, the resource files weren't found either (localisation) but a rebuild-all worked just fine :)

**Comment by lauren-mills** [comment]
The localization actually looks at the intro card, rather than the greeting since we moved greeting into QnA Chitchat

**Comment by lauren-mills** [comment]
@darrenj added the telemetry changes

**Comment by ryanisgrig** [comment]
Adding `new` keyword to the telemetry changes is correct and is used in [`Microsoft.Bot.Solutions`](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Middleware/Telemetry/TelemetryLuisRecognizer.cs#L55), the base recognizer is called inside the internal method.

**Review by darrenj — APPROVED** [review]

**Pull request merged**
