### PR TITLE
[Docs] add bing search box

### LINKED ISSUE #3035: [Docs] add search ability
## User Story
As ... anyone
I want ... to search the docs
so that ... it is easy to navigate

## Acceptance Criteria 
*List your requirements.*
- [ ] ... a search box is added

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*

* https://azure.microsoft.com/en-us/services/cognitive-services/bing-custom-search/
  - This one needs a server
* https://rgardler.github.io/2015/07/25/adding-bing-search-to-a-website

## Notes
*Provide any additional information.*

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

Close #3035

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Follow second approach. However, css needs to be tuned:
image

It will open a new tab:
image

Note: if use q1 for site, site will not be displayed in search input. So use onsubmit to modify q.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Review by ryanisgrig — APPROVED** [review]
👍

**Review by lauren-mills — APPROVED** [review]

**Comment by lauren-mills** [comment]
@ryanlengel @xieofxie Can we make this change against master? Seems like the sooner the better for this 😎

**Comment by lauren-mills** [comment]
@xieofxie - Also can you add a screenshot of what it looks like after you search? Does it open a new page?

**Comment by xieofxie** [comment]
@lauren-mills Changed to master. Will open a new tab and see pic in pr's description.

**Review by darrenj — APPROVED** [review]

**Pull request merged**
