### PR TITLE
[TypeScript][Template/Sample] Migrate latest functionalities 

### PR DESCRIPTION
**Pull request by DiegoCardozo94**
## Purpose
_What is the context of this pull request? Why is it being done?_

Increase parity between the `C#` and `TypeScript` implementation of:
- Template/Sample
	- Assistant
	- Skill
	
## Changes
_Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)_

- Migrate changes from `C#` implementation (up to 478d627) to `TypeScript`

## Feature Plan
_Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues._

This PR is part of the improvement of parity. The `PR #1933` comes before this one, which updates the `BotBuilder-Libs`, and this one updates the `Samples` and `Templates`.

Checklist
*-*
#### Deployment Scripts
- [X] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [X] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Review by darrenj — APPROVED** [review]

**Comment by DiegoCardozo94** [comment]
Hi @darrenj, should we leave this PR pointing to branch `master`? Or we should change this PR to point branch `next`?  Thanks.

**Review by ryanisgrig — APPROVED** [review]

**Comment by lzc850612** [comment]
i feel like this change should go to next branch since it's features due for release in next version. @darrenj?

**Comment by darrenj** [comment]
It's to catch-up parity with C# as typescript is lagging slightly. My vote is for master as it's a typescript change which we want to fast-track to provide more stable VA typescript features today. If it were C# I would agree but my vote is to fast-track typescript alignment/fixes unless there is a strong feeling otherwise?

**Review by lzc850612 — APPROVED** [review]

**Comment by DiegoCardozo94** [comment]
Hi @lzc850612,

Apologies for not seeing this issue before. We created this branch out of `next` and the conflicts appeared when the base branch was changed to `master`. We'll rebase the branch with master so the `C#` changes are not included in these PR.

**Pull request merged**
