### PR TITLE
[TypeScript][Virtual Assistant] Add Functional Tests

### PR DESCRIPTION
**Pull request by Batta32**
Related to #3290 

### Purpose
*What is the context of this pull request? Why is it being done?*
There is no functional test applied for Virtual Assistant in TypeScript.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
- Copy and adapt C# VA functional test as the responses' length between C# and TS are different
- Add yml file for the TypeScript VA

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
\-

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [X] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

### CODE REVIEW

**Review by darrenj — APPROVED** [review]
Looks great - thanks for this! let's create a tracking task to add some docs to enable us to showcase what this helps enable.

**Comment by Batta32** [comment]
Thanks @darrenj, we will be adding some docs demonstrating the benefits of having this!

**Comment by Batta32** [comment]
@darrenj - we already created/updated the documentation!

**Review by lauren-mills — APPROVED** [review]

**Comment by Batta32** [comment]
We closed this issue and reopened PR #3736 as we don't have permissions to push in this branch.

**Pull request closed without merging**
