### PR TITLE
Update App Insights Telemetry usage in all Skills

### LINKED ISSUE #1484: Power BI Conversational Analytics Sample User Utterance field not dispaying in Transcript report
## Project

**Name**: ConversationalAnalyticsSample_4_4.pbit (Conversational Analytics Power BI sample)

**Language**: N/A

## Description
When you connect Application Insights to the Power BI sample ConversationalAnalyticsSample_4_4.pbit and open the Transcript tab the User Utterance field does not display the utterances. 

## To Reproduce
Download the Power BI sample here (https://github.com/microsoft/botframework-solutions/blob/master/solutions/analytics/ConversationalAnalyticsSample_4_4.pbit). Use your Application Insights Application Id from the Portal (API Access tab under the Application Insights service). 

## Expected behavior
Once connected to the Power BI report and you navigate to the Transcripts tab, you should see the User Utterances displayed for the appropriate Bot Responses.

### LINKED ISSUE #1556: Update App Insights Telemetry usage in all Skills
## Description

Apply the changes at #1560 to each skill:
- [x] Skill Template
- [x] Calendar
- [x] To-Do
- [x] Email
- [x] Weather
- [x] News
- [x] Search
- [x] Point of Interest
- [x] Automotive

## Expected behavior

On a VA with remote skills, the Power BI sample works out of the box with no error of missing properties (DialogInstanceId). In this case, a remote skill will log the correct dialog name and instance id.

### PR DESCRIPTION
**Pull request by DingmaomaoBJTU**
## Description

Closes #1556 
Closes #1484 

### Bug Fixes

Update telemetry implementation in all skills and update script accordingly.

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the appropriate unit tests
- [ ] I have tested any new/updated dialogs using Speech in the emulator to ensure the [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) property is set to enable a high quality speech-first experience and the appropriate [InputHints](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) are set correctly. 
- [ ] I have updated related documentation

- [x] A duplicate issue is filed to track future  work.

- [ ] All languages have been updated
- [ ] You have tested deployment with your new models

### CODE REVIEW

**Comment by DingmaomaoBJTU** [comment]
@lauren-mills I saw the deploy.ps1 file has some new updates in skill template compared to individual skills. Do we need to apply the new updates to each skill?

**Comment by ryanisgrig** [comment]
Can you validate that the Power BI template works with these changes? You should just need:
1. Virtual Assistant
2. Add one skill (any should work)
3. New Application Insights instance
4. Install template from https://aka.ms/botPowerBiTemplate
5. Run a couple of queries to the VA (QnA, trigger the skill, trigger a waterfall dialog)
6. After data has populated in app insights, validate that Power BI is able to make the queries without any errors.

**Comment by darrenj** [comment]
@DingmaomaoBJTU - Good spot, yes any changes to the skill deploy.ps1 should be replicated across the skills if they have diverged. Thanks!

**Comment by DingmaomaoBJTU** [comment]
@ryanlengel Verified and no error pop up~ @darrenj All scripts are updated!

**Comment by darrenj** [comment]
Thanks!

**Pull request merged**
