### PR TITLE
[TypeScript][VA/Skill] Integrate specific cultures

### PR DESCRIPTION
**Pull request by DiegoCardozo94**
**This Pull Request will be present in the next release.**

## Purpose

_What is the context of this pull request? Why is it being done?_

We updated the _Virtual Assistant_ and the _Skill_ language cultures to improve the functionality of the **multilanguage** implementation. 

## Changes
_Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)_

- Implement `fallback to root language` functionality
- Rename different folder and files with a specific _locale_ name
- Use of the specific _locale_ name for the _deployment scripts_ files
- Changes in _mainDialog_ implementation to obtain the new locale language cultures (eg. 'en-us').
- Update templates to include the new changes when generate a new VA and Skill samples.

## Tests
_Is this covered by existing tests or new ones? If no, why not?_
It's covered by _LocalizationTests_, _MainDialogTests_ files.

## Testing steps

1. Deploy a _Virtual Assistant_ with both languages (eg. _en-us, es-es_).
2. Verify in the bot solution that the resource folder contains the specific cultures.
3. Execute the _Virtual Assistant_ with any of the deployed specific cultures
4. Check the behavior of the _Virtual Assistant_ communication

## Feature Plan
_Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues._
*-*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [x] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [X] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [X] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [X] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by DiegoCardozo94** [comment]
We noticed that this PR contains conflicts, we'll update fixing the merge conflicts.

**Comment by DiegoCardozo94** [comment]
Hi team, this Pull Request is ready for review.

**Review by ryanisgrig — APPROVED** [review]

**Comment by ryanisgrig** [comment]
@lauren-mills take a look when you get a chance, I remember you had some concerns about language cultures in the past but can't recall if it related to this?

**Comment by Batta32** [comment]
Hi @lauren-mills, we implemented the **fallback to root language**, please take a look at it. 
We will add the necessary tests to cover this feature.

Just to be sure, these are the repro steps that we followed:

1. Deploy a Virtual Assistant with `en-us`.
1. Change the configuration in the emulator to a non-existing locale, in this case `en-gb`.
1. Talk to the bot and check if the activity sent have the locale `en-gb`.
image

4. The bot will fallback to `en` root language and answer correctly.

**Review by lzc850612 — APPROVED** [review]

**Comment by Batta32** [comment]
Hi team, we already solved the merge conflicts.

**Review by lauren-mills — APPROVED** [review]

**Comment by DingmaomaoBJTU** [comment]
@Batta32 Hi Batta, when will the new pkg contains this change being published?

**Pull request merged**
