### PR TITLE
Refactor Libraries directories to SDK format

### PR DESCRIPTION
**Pull request by ryanisgrig**
### Purpose
*What is the context of this pull request? Why is it being done?*
#1787 
```
\sdk
    \csharp
        \build
        \libraries
            \microsoft.bot.builder.solutions.skills
            \microsoft.bot.builder.solutions
        \tests
            \microsoft.bot.builder.solutions.skills.tests
            \microsoft.bot.builder.solutions.tests
        Microsoft.Bot.Builder.Solutions.sln
    \typescript
        \libraries
            \botbuilder-skills
            \botbuilder-solutions
```

```
\build
    build.botbuilder-libs.ts.ps1
    build.botskills.ts.ps1
    build.generator-assistant.ps1
```

* Remove `VirtualAssistant.ruleset` at root
* Update YAML files with references to new locations
* Update .ps1 files with references to new locations

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### CODE REVIEW

**Comment by gabog** [comment]
I think microsoft.bot.builder.skills and microsoft.bot.builder.solutions should be pushed into up into a libraries folder so we can have a dirprops at the root.

should be something like:
image

**Comment by ryanisgrig** [comment]
@gabog, I see - that makes sense. With that I'm okay with renaming the root \libraries folder to \sdk so it isn't redundant. The output would be:

```
\sdk
    \csharp
        \build
        \libraries
            \microsoft.bot.builder.skills
            \microsoft.bot.builder.solutions
        \tests
            \microsoft.bot.builder.skills.tests
            \microsoft.bot.builder.solutions.tests
        Microsoft.Bot.Builder.Solutions.sln
    \typescript
        \libraries
            \botbuilder-skills
            \botbuilder-solutions
```

**Comment by dfavretto** [comment]
Hey @ryanlengel be aware that the TypeScript [build scripts](https://github.com/microsoft/botframework-solutions/blob/af1115ad52b811efaeb9afebff17726cbb579bfb/build.botbuilder-libs.ts.ps1) and the Pipelines YAML files (both [C#](https://github.com/microsoft/botframework-solutions/tree/af1115ad52b811efaeb9afebff17726cbb579bfb/yaml/csharp) and [TypeScript](https://github.com/microsoft/botframework-solutions/tree/af1115ad52b811efaeb9afebff17726cbb579bfb/yaml/typescript)) should be modified with the new paths.

image


image

**Comment by gabog** [comment]
I like the updated tree.
One more thing. Would it be possible to rename *.builder.skills to *.builder.solutions.skills?
Thanks

**Review by gabog — CHANGES_REQUESTED** [review]
A couple of issues I found for the C# version:

1. The Skills project doesn't load when I open the solution file:
image

2. The project name for Microsoft.Bot.Builder.Solutions.Skills.Tests is fine, but the underlying folder is still Microsoft.Bot.Builder.Skills.Tests.

**Review by gabog — APPROVED** [review]

**Review by lauren-mills — APPROVED** [review]

**Pull request merged**
