### PR TITLE
[C#][VA & Skill] Replace AzureBlobTranscriptStore references to BlobsTranscriptStore

### LINKED ISSUE #3613: [C#][VA & Skill] Replace AzureBlobTranscriptStore references to BlobsTranscriptStore
## User Story
As SDK R10 dotnet release was published
I want to rename the `AzureBlobTranscriptStore` with the new `BlobsTranscripStore` in C# bots

## Acceptance Criteria 
*List your requirements.*
- [X] Update the references of `AzureBlobTranscriptStore` to `BlobsTranscripStore` in the [DefaultAdapter](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Adapters/DefaultAdapter.cs) of Virtual Assistant Sample
- [X] Update the references of `AzureBlobTranscriptStore` to `BlobsTranscripStore` in the [DefaultAdapter](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/skill/SkillSample/Adapters/DefaultAdapter.cs) of Skill Sample
- [X] Validate the behavior of `BlobsTranscripStore`
- [X] Replicate the changes to templates

## Resources
*Provide any screenshots or conversation mockups to support your request.*
*Learn how to mock up bot conversations with [.chat files](http://aka.ms/bfchatfile).*
- Use [Microsoft.Bot.Builder@4.10.0](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.10.0)
- Use [BlobsTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs)

## Notes
*Provide any additional information.*
\-

### PR DESCRIPTION
**Pull request by Batta32**
Fixes #3613

### Purpose
*What is the context of this pull request? Why is it being done?*
The new [Microsoft.Bot.Builder.Azure](https://www.nuget.org/packages/Microsoft.Bot.Builder.Azure/4.10.0) package has been released.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
- Replace references of `AzureBlobTranscriptStore` to `BlobsTranscriptStore` in the C# Virtual Assistant and the C# Skill
- Replicate changes to the C# Templates

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
We manually tested the [botbuilder@4.10.0](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.10.0) updating the references of `AzureBlobTranscriptStore` to `BlobsTranscriptStore` and it correctly worked.

image

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

### CODE REVIEW

**Review by peterinnesmsft — APPROVED** [review]
Looks good! Just to confirm, I am assuming there will be another iteration to this PR once the final package versions have been published for the R10 SDK?

**Comment by Batta32** [comment]
@peterinnesmsft - Yes! As soon as the R10 is published, we will do another end-to-end test in order to confirm these changes. I'll change this PR to draft so we can confirm this 😊.

**Comment by Batta32** [comment]
@peterinnesmsft - we successfully confirmed that these changes works using the stable version of `botbuilder@4.10.0`. We will move this PR ready to be merged!

**Review by peterinnesmsft — APPROVED** [review]

**Review by pavolum — APPROVED** [review]

**Comment by mrivera-ms** [comment]
@peterinnesmsft, is this item ready to merge? Could you please update it with status? Thank you.

**Pull request merged**
