### PR TITLE
Microsoft.Bot.Solutions: Correct capitalization of folder name

### PR DESCRIPTION
**Pull request by outofthecave**
Is there a way we can prevent the lowercase folder `microsoft.bot.solutions` from being created again and instead get people (and their IDE's) to create new files in the correctly capitalized folder instead?

### CODE REVIEW

**Comment by lauren-mills** [comment]
Due to the differences in how GitHub and the file system treat capitalization (GitHub treats them as different folders, Windows treats them as the same folder) the only way we've found to do it is to delete the folder and do a check in, then add it back and check in again. I'll leave it up to @darrenj to decide what the capitalization should be.

**Comment by outofthecave** [comment]
Thanks.  Unfortunately, the build doesn't work for me if it's lowercase.  Should it be working?

**Comment by lzc850612** [comment]
> Thanks. Unfortunately, the build doesn't work for me if it's lowercase. Should it be working?

can you add some more information on what exactly it fails on in your local environment if it's lowercase? it should build.

**Comment by enzocano** [comment]
Hi @lzc850612, the issue only occurs in unix environments.

* Repo cloned with `git clone https://github.com/Microsoft/AI.git` from `CMD`:
image

* Repo cloned with `git clone https://github.com/Microsoft/AI.git` from `bash` (also with git-bash in Windows):
image

Comparison between solutions

image

**Comment by lzc850612** [comment]
> Hi @lzc850612, the issue only occurs in unix environments.
> 
> * Repo cloned with `git clone https://github.com/Microsoft/AI.git` from `CMD`:
>   image
> * Repo cloned with `git clone https://github.com/Microsoft/AI.git` from `bash` (also with git-bash in Windows):
>   image
> 
> Comparison between solutions
> 
> image

thanks Enzo. Yeah the problem is that we now have two folder with same name and only different in casing. this can be fixed and we should keep the lowercase folder. i'll fix it.

**Comment by outofthecave** [comment]
@lzc850612 If I try to build from the current master branch, I get errors for the classes that are in the lowercase folder:
image
If I apply the capitalization change from this PR, my build works fine.

**Comment by lzc850612** [comment]
> @lzc850612 If I try to build from the current master branch, I get errors for the classes that are in the lowercase folder:
> image
> If I apply the capitalization change from this PR, my build works fine.

Hi @outofthecave , yeah i understand that'll work. however we need to change the folder to be lowercase to match our current convention. your change changed everything to uppercase which is not the convention.

**Comment by lzc850612** [comment]
I have just changed the folder back microsoft.bot.solutions and there's only one folder now. Please see if it builds for your system.

**Comment by enzocano** [comment]
Hi @lzc850612, you should modify the [VirtualAssistant.sln](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/src/csharp/VirtualAssistant.sln#L8) to use the new directory, also I think the same directory is used in several places and all of them need to be updated.

Related: Do the folders at [solutions/Virtual-Assistant/src/csharp/tests](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/tests) use lowercase or are they fine on PascalCase?

**Comment by lzc850612** [comment]
> Hi @lzc850612, you should modify the [VirtualAssistant.sln](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/src/csharp/VirtualAssistant.sln#L8) to use the new directory, also I think the same directory is used in several places and all of them need to be updated.
> 
> Related: Do the folders at [solutions/Virtual-Assistant/src/csharp/tests](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/tests) use lowercase or are they fine on PascalCase?

Thanks. I'll make the change for the solution file.

I think the folders under tests should be lower case also, but let's fix that some other time.

**Comment by lzc850612** [comment]
> > Hi @lzc850612, you should modify the [VirtualAssistant.sln](https://github.com/Microsoft/AI/blob/master/solutions/Virtual-Assistant/src/csharp/VirtualAssistant.sln#L8) to use the new directory, also I think the same directory is used in several places and all of them need to be updated.
> > Related: Do the folders at [solutions/Virtual-Assistant/src/csharp/tests](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/tests) use lowercase or are they fine on PascalCase?
> 
> Thanks. I'll make the change for the solution file.
> 
> I think the folders under tests should be lower case also, but let's fix that some other time.

i have just made the change to change to lowercase folder name for the solution file. Can you try build again?

**Comment by enzocano** [comment]
@lzc850612, it seems that some files should still be updated, I created #813 with the changes.

**Comment by lzc850612** [comment]
> @lzc850612, it seems that some files should still be updated, I created # 813 with the changes.

Thanks. I just approved and merged it.

**Comment by outofthecave** [comment]
`master` builds for me now.  Thanks!

**Pull request closed without merging**
