### PR TITLE
[Botskills] Support New Manifest Schema

### PR DESCRIPTION
**Pull request by Batta32**
### Purpose
*What is the context of this pull request? Why is it being done?*
A new manifest schema was released so it should be supported by the Botskills CLI Tool.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
* Support the old a new manifest file formats (new models)
* Support a local LU file (as `file://` in the new manifest schema)
* The `authentication` process/creation was skipped
* Use appsettings.json of the Virtual Assistant for the skill's registration, populating the `appId`, `endpoint` and `id` of the skill
* Add `--endpointName` argument to choose the desired endpoint

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
They are not currently covered by tests. It's in the feature plan in order to finish with this feature.

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
We will continue updating the documentation, fixing tests, updating the VA/Skill.

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by Batta32** [comment]
@darrenj - should we remove the entire [authentication](https://github.com/microsoft/botframework-solutions/pull/2921/files#diff-35cc53bfb9115139e6f1d83289366fddR458) process, which is commented in this PR?

**Comment by lzc850612** [comment]
I'm testing this locally and seeing that the skills.json file is not being modified with the skill's information. I can see that the skill content is being added to the end of appsettings.json file but it should be in skills.json file. Can you merge your branch with the latest of next so you can see the skills.json with the sample content: https://github.com/microsoft/botframework-solutions/blob/next/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/skills.json and make sure the botskills tool will generate the right content in there so after connecting to a skill skills.json is correctly configured? Thanks.

**Comment by darrenj** [comment]
@lzc850612 Should we not snap to app settings.json as per SDK direction. Skill contents are much smaller so the main reason for separating before doesn’t apply?

**Comment by lzc850612** [comment]
> @lzc850612 Should we not snap to app settings.json as per SDK direction. Skill contents are much smaller so the main reason for separating before doesn’t apply?

The thing that makes me want to separate the skills stuff out to a separate json file is the SkillHostEndpoint part:

{
  **"SkillHostEndpoint": "https://vasampletest-xmxqanr.azurewebsites.net/api/skills/",**
  "BotFrameworkSkills": [
    {
      "Id": "EmailSkill",
      "AppId": "7b0ebd75-a547-4931-b005-230838a3b6a0",
      "SkillEndpoint": "https://emailskilltest08-rcgh23k.azurewebsites.net/api/messages"
    },
    {
      "Id": "ToDoSkill",
      "AppId": "7adfac6b-459c-44b9-8c77-bd4c58f015a0",
      "SkillEndpoint": "https://todoskilltest08-skpmopd.azurewebsites.net/api/messages"
    }
  ]
}

the SkillHostEndpoint is mandatory otherwise the skill scenario would not work. I think it's better to have everything related to skills in skills.json especially with the SkillHostEndpoint as something that's not part of the 'core' appsettings, but I'm OK with all them being in appsettings.json.

Also, i think we should add the functionality of setting the SkillHostEndpoint property in appsettings/skills.json into botskills. when botskills is running it should have access to the bot's azure app since the appsettings.json would have msappid&password in there. we just have to see if there's an API to get the bot messaging endpoint and change the last part to be api/skills. if there's no API we could always just do {webAppName}.azurewebsites.net/api/skills. this will make everything working end to end.

**Comment by lzc850612** [comment]
I will remove the skills.json file so everything's going to be in appsettings.json.

@Batta32 please evaluate the work on populating the SkillHostEndpoint property. Thanks.

**Comment by lzc850612** [comment]
Just found a potential issue. When botskills runs it will populate the skill configuration with this block:

{
      "Id": "EmailSkill",
      "AppId": "7b0ebd75-a547-4931-b005-230838a3b6a0",
      "SkillEndpoint": "https://emailskilltest08-rcgh23k.azurewebsites.net/api/messages"
},

However the SkillSwitch feature will not work if there's no 'Name' property in this block. Can you make sure the botskills tool will add the Name property as well? There's a bigger issue of localizing it that we've raised an issue to the core SDK team to figure out because that's really where this should be resolved. in the meantime let's just populate the Name property with the same content of Id to make sure the SkillSwitch feature works. Thanks!

**Comment by Batta32** [comment]
@lzc850612 & @darrenj:
1. `SkillHostEndpoint`
    * Should this property be populated by the botskills after the connection of the first Skill to the Virtual Assistant? Or is it better to populate it in the `deploy.ps1` as it will contain `{webAppName}.azurewebsites.net/api/skills structure`?
    * We will be populating this property in the connection command of Botskills, validating if it's already added or not
    * We will be analyzing if it's an API to get the bot messaging endpoint and change the last part to be `api/skills `

2. `Name`
    * We will add the `Name` property of the Skill with the same content of Skill's Id to make sure the SkillSwitch feature works

**Review by lzc850612 — APPROVED** [review]

**Review by darrenj — APPROVED** [review]

**Pull request merged**
