### PR TITLE
[POI] use activity handler

### PR DESCRIPTION
**Pull request by xieofxie**
### Purpose
*What is the context of this pull request? Why is it being done?*

POI uses activity handler

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

* Add TelemetryInitializerMiddleware
* Use DefaultActivityHandler instead of DialogBot
* Use ActivityHandlerDialog instead of RouterDialog
* Tests use LuisRecognizer

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

### CODE REVIEW

**Comment by xieofxie** [comment]
hi, @lauren-mills, do you have a plan for [this](https://github.com/microsoft/botframework-solutions/issues/2584) ? Otherwise all events sent will be responded by a complete message. Thanks~

**Review by lauren-mills — APPROVED** [review]

**Comment by xieofxie** [comment]
As this is in progress https://github.com/microsoft/botframework-solutions/issues/2584, I skip sending Handoff in OnDialogCompleteAsync for location event in code.

**Comment by lauren-mills** [comment]
Yes, @xieofxie, I made this change in the VA template to handle it: https://github.com/microsoft/botframework-solutions/blob/86e9dcd3c8bdb0948384ad614dbc90c3257fb721/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Dialogs/MainDialog.cs#L344

**Comment by xieofxie** [comment]
@lauren-mills OK, I changed to SuppressCompletionMessage too.
And I just thought EoC should always be sent by VA/Skill whenever it is finished (i.e. no active dialog) process some activity.
In this way, they can both be used as a callee bot and caller could always know if they are still active.

**Pull request merged**
