### PR TITLE
[POI] Use choice prompt for POI selection & prompt user for current location if they are missing the IPA.Location event

### LINKED ISSUE #783: [POI] POI skill cannot get list for some utterance
**Description**
Example) **find asian restaurant** - is not working

**To Reproduce**
image

**Expected behavior**
Have to show asian restaurant list near location

### PR DESCRIPTION
**Pull request by ryanisgrig**
### Bug Fixes
Fix #783 where "fix KEYWORD" utterances were mapped to None.

### Conversational Experience
Close ##572: use the ChoicePrompt when POIs are displayed to allow a user to select by name, address, number, & ordinal.
Close ##755: if IPA.location event is not sent, the VA will prompt user for their current location. This runs an Azure Maps fuzzy query on their entire response and asks users to select the best match. The bot then continues to their original intent (find POI, find parking, route to...).
* Updated responses for improved speak properties
* Updated POI card with route info card

image

image

## Testing Steps

User: Send utterance to trigger POI
Bot: Where are you now?
User: Send location like an address or description "city center plaza in bellevue"
Bot: *look up with fuzzy search and send choice prompt*
User: *select option and continue with normal dialog*

Validate with new uploaded sample transcript

## Checklist

- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added or updated the appropriate unit tests
- [X] I have tested any new/updated dialogs using Speech in the emulator to ensure the [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) property is set to enable a high quality speech-first experience and the appropriate [InputHints](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) are set correctly. 
- [X] All languages have been updated
- [X] You have tested deployment with your new models

### CODE REVIEW

**Comment by darrenj** [comment]
Looks good, the location prompt is pretty clever in that if I say "city center plaza in bellevue" or "chippenham in the UK" it works but if I'm (lazy) and just say Seattle or London it says

image

Which one is a little confusing as it's not giving me any options, so perhaps a try again or something? 

- If there is a easy way to get seattle, london, berlin, etc. working that would be great or we have this as a known issue.
- Either way - I would provide an example of something that works to guide the user that it's actually quite intelligent, e.g. city center plaza in bellevue"

**Comment by darrenj** [comment]
Added a simple change to the appsettings.json file as the secret config entry had an old name

**Review by darrenj — DISMISSED** [review]
Looks good, the location prompt is pretty clever in that if I say "city center plaza in bellevue" or "chippenham in the UK" it works but if I'm (lazy) and just say Seattle or London it says

image

Which one is a little confusing as it's not giving me any options, so perhaps a try again or something? 

- If there is a easy way to get seattle, london, berlin, etc. working that would be great or we have this as a known issue.
- Either way - I would provide an example of something that works to guide the user that it's actually quite intelligent, e.g. city center plaza in bellevue"

**Comment by ryanisgrig** [comment]
@darrenj it looks like just a city name like "Seattle" is captured as a Cancel intent. Opened #943 to track it. Afterwards, we may need to filter properly (it probably doesn't come back as a POI or Street Address type from Azure Maps, but that will require us to follow through the steps that it is rendered correctly)

**Review by darrenj — APPROVED** [review]

**Pull request merged**
